apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["yarn"]
          args: ["run", "migrate:deploy"]
          env:
            - name: "MYSQL_ROOT_USER"
              value: root
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: {{ .Values.mysql.auth.existingSecret }}
            - name: "MYSQL_DATABASE"
              value: {{ .Values.mysql.auth.database }}
            - name: "DATABASE_URL"
              value: "mysql://$(MYSQL_ROOT_USER):$(MYSQL_ROOT_PASSWORD)@logic-server-mysql.ajou-coding-hub:3306/$(MYSQL_DATABASE)"
