apiVersion: v1
kind: ServiceAccount
metadata:
  name: logic-server-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logic-server
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logic-server
subjects:
  - kind: ServiceAccount
    name: logic-server-account
roleRef:
  kind: Role
  name: logic-server
  apiGroup: rbac.authorization.k8s.io